config/routes.rb
Rails.application.routes.draw do

  ### Internal routes for apps communications
  namespace :hooks do
    post '/screenshot' => 'heatmaps#screenshot'
  end
  # collector resources !!!!!
  post 'collect' => 'api/sdk/v1/collect#index'

  namespace :api do
    namespace :ext do
      namespace :v1 do
        get 'views' => 'views#index'
      end
    end
  end

  devise_for :users, path: 'accounts'

  if ENV["UNK_APP_IS_BILLABLE"]
    # TODO remove this
    post '/billing/webhook' => 'billings/webhook'
  end

  authenticate :user do
    # dashboard
    namespace :dashboard do
      get '/' => 'stats#index'
      get '/notify' => 'notifications#notify'
      get '/domains/received-invitations' => 'domains_teams#received_invitations'
      post '/domains/accept-invitation/:domain_id' => 'domains_teams#accept_invitation', as: 'accept_admin_invitation'
      delete '/domains/decline-invitation/:domain_id' => 'domains_teams#decline_invitation', as: 'decline_admin_invitation'

      # accounts and subscribe
      get 'account/plan/current' => 'plan#current_plan'
      get 'account/plan/current/upgrade' => 'plan#upgrade'
      get 'account/plan/current/confirm-upgrade' => 'plan#upgrade'
      get 'account/plan/subscribe' => 'plan#subscribe'
      post 'account/plan/confirm-subscribe' => 'plan#confirm_subscribe'

      # change current domain
      post '/set-current-domain' => 'dashboard#set_current_domain'

      # stats for current domain
      scope :stats, as: 'stats' do
        get '/' => 'stats#overview'
        %w(summary pages devices events errors geo heatmaps export).each do |route|
          get "/#{route}" => "stats##{route}"
        end
      end

      # domains resources
      resources :domains do
        member do
          get 'settings'
          post 'settings'
        end
        member do
          scope :team, as: 'team' do
            get '/' => 'domains_teams#index'
            delete '/delete/:admin_domain_id' => 'domains_teams#delete_member', as: 'delete_member'
            get '/new' => 'domains_teams#new'
            post '/' => 'domains_teams#invite', as: 'invite'
            get '/sent-invitations' => 'domains_teams#sent_invitations'
          end
        end
        resources :api_keys
      end
    end
    # api
    namespace :api do
      get '/overview' => 'overview#index'
      get '/overview/top_pages' => 'overview#top_pages'
      get '/pages/summary' => 'pages#summary'
      get '/pages/views' => 'pages#views'
      get '/pages/weekly_by_days' => 'pages#weekly_by_days'
      get 'pages/:page_id/views' => 'pages#page_views_details'
      get '/geo' => 'geo#index'
      get '/devices' => 'devices#index'

      get '/errors' => 'errors#index'

      # TODO
      get '/events' => 'events#index'
      # clicks and events
      get '/heatmaps' => 'heatmaps#index'
      get '/export' => 'export#index'
      post '/export/pdf' => 'export#as_pdf'
    end

    # admin
    namespace :admin do
      get '/' => 'admin#index'
      resources :users, only: [:index, :show]
      resources :contacts, only: [:index, :show]
    end

    get '/subscription' => 'dashboard/subscription#index'
  end

  authenticated :user do
    scope :welcome do
      root 'welcome#pages', as: 'home_auth_path'
    end
    root 'dashboard/stats#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#pages', as: 'home_path'

  post '/contact' => 'contact#contact_us'
  get '/contact/' => 'contact#index'

  mount Sidekiq::Web => '/sidekiq'

  get "/:page" => "welcome#pages", :as => 'public_pages'

end

app/views/shared/_admin_menu.html.erb
<nav class="menu">
  <ul class="menu-list mt-1">
    <li>
      <%= link_to(admin_path, class: current_menu_item_class?(admin_path) + ' ' + current_menu_item_class?('/')) do %>

        <%= t('admin.sidebar.admin') %>
      <% end %>
    </li>
    <li>
      <%= link_to(admin_users_path, class: current_menu_item_class?(admin_users_path) + ' ' + current_menu_item_class?('/')) do %>

        <%= t('admin.sidebar.users') %>
      <% end %>
    </li>
    <li>
      <%= link_to(admin_contacts_path, class: current_menu_item_class?(admin_contacts_path)) do %>

        <%= t('admin.sidebar.contacts') %>
      <% end %>
    </li>
  </ul>

</nav>

app/views/shared/_disclaimer.html.erb
<p class="notice">
  Disclaimer :<br/>
  - This version is for beta test purpose only.<br/>
  - This is an early beta release, please note some services are not yet implemented neither functional.<br/>
  - All services are free, the subscription module is not yet configured.<br/>
  - Emails module is not yet implemented. Some service may not works<br/>
  - All data, information may be lost or removed at any time without any further notice<br/>
</p>

app/views/shared/_footer_logged_in.html.erb
<style>
  .app_footer {
    margin-top: auto;
    margin-bottom: 16px;
    font-size: 14px;
  }

  .app_version, .copy {
    font-weight: 700;
    font-size: 12px;
  }

  .app_version {
    padding-left: 1.5rem;
  }
</style>
<footer class="app_footer">
  <div class="container">
    <hr/>
    <div class="columns">
      <div class="column app_version">
        <span>Unknown Analytics <%= ENV['APP_VERSION'] || 'Beta' %></span> /
        <span class="is-size-7">Build <%= ENV['BUILD_VERSION'] || 'Beta' %></span>
      </div>

      <div class="column has-text-centered copy">
        <span translate="">© <%= Date.today.strftime("%Y") %> unknown Analytics - <small> <a href="https://www.380squares.xyz">380Squares</a></small> </span>
      </div>
      <div class="column has-text-right">
        <ul>
          <li>

            <%= link_to t('Support'), contact_path(subject: "[Support]") %>
            ·
            <%= link_to t('Help'), contact_path(subject: "[Help]") %>
            ·
            <%= link_to t('Feedback'), contact_path(subject: "[Feedback]") %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="<%= root_path %>">
        <%= render "shared/logo" %>
      </a>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-end">

      <div class="navbar-item">
        <%= render 'shared/header/features_dropdown_navbar' %>
      </div>

      <div class="navbar-item">
        <%= link_to t('Principles'), (user_signed_in? ? home_auth_path_path : '/') + "#principles", class: "title is-6" %>
      </div>
      <div class="navbar-item">
        <%= link_to t('Pricing'), (user_signed_in? ? home_auth_path_path : '/') + "#pricing", class: "title is-6" %>
      </div>
      <div class="navbar-item">
        <%= link_to t("Integration"), (user_signed_in? ? home_auth_path_path : '/') + "#sdk_integration", class: "title is-6" %>
      </div>
    </div>
    <div class="navbar-item">
      <% if user_signed_in? %>
        <%= link_to "Dashboard", dashboard_path, class: "has-text-weight-bold" %>
      <% else %>
        <div class="buttons">
          <%= link_to(new_user_registration_path, class: "button is-primary register-button") do %>
            <strong> <%= t('Sign up') %></strong>
          <% end %>
          <%= link_to(new_user_session_path, class: "button is-light") do %>
            <strong> <%= t('Log in') %></strong>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_header_account.html.erb
<nav class="navbar" id="dashboard_navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="<%= root_path %>">
          <%= render "shared/logo" %>
        </a>
      </div>
    </div>
    <div class="navbar-end">

      <%= render "shared/header/top_right_settings" %>

    </div>

  </div>
</nav>

app/views/shared/_header_dashboard.html.erb
<nav class="navbar" id="dashboard_navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="<%= root_path %>">
          <%= render "shared/logo" %>
        </a>
        <!--<form id="navbar_header_form" class="navbar-item">
          <div class="mt-4">
            <app-v-typehead :list="commands"
                            placeholder="Shortcut"
                            v-on:selected="changeFilterPath($event)">
            </app-v-typehead>
          </div>
        </form>-->
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <% if current_domain.present? %>
          <span class="tag  is-black"><%= current_domain.name %></span>

        <% end %>
      </div>


      <%= link_to('/guide', class: "navbar-item") do %>
        Guide
      <% end %>
      <div class="navbar-item has-dropdown is-hoverable">
        <div class="navbar-link top-header-notifications has-notifications">
          <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-notification'} %>
        </div>
        <div class="navbar-dropdown">
        </div>
      </div>
      <%= render "shared/header/top_right_settings" %>

    </div>

  </div>
</nav>

app/views/shared/_icon.html.erb
<svg viewBox="0 0 24 24" class="icon <%= defined?(svg_class) ? svg_class : '' %>">
  <use xlink:href="<%= '#' + icon %>" class="<%= defined?(css_class) ? css_class : 'icon' %>"></use>
</svg>

app/views/shared/_logo.html.erb
<strong>Unknown Analytics &nbsp;<span class="tag is-danger">Beta</span> </strong>

app/views/shared/_menu.html.erb
<nav class="menu">
  <% unless current_domain.nil? %>
    <ul class="menu-list mt-1">
      <li>
        <%= link_to(dashboard_path, class: current_menu_item_class?(dashboard_path) + ' ' + current_menu_item_class?('/')) do %>
          <% cache('icon-dashboard') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-dashboard' } %>
          <% end -%>
          <%= t('dashboard.menu.overview') %>
        <% end %>
      </li>
      <li>

        <%= link_to(dashboard_stats_pages_path, class: current_menu_item_class?(dashboard_stats_pages_path)) do %>
          <% cache('icon-monitor') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-monitor' } %>
          <% end -%>
          <%= t('dashboard.menu.pages_views') %>
        <% end %>
      </li>
      <!--<li>

                </li>-->
      <li>
        <% if current_domain.domain_setting.track_geo %>
          <%= link_to(dashboard_stats_geo_path, class: current_menu_item_class?(dashboard_stats_geo_path)) do %>
            <% cache('icon-globe') do %>
              <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-globe' } %>
            <% end -%>
            <%= t('dashboard.menu.geo_scattering') %>
          <% end %>
        <% else %>
          <%= link_to(settings_dashboard_domain_path(current_domain)) do %>
            <% cache('icon-globe') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-globe' } %>
           <% end -%>
            <%= t('dashboard.menu.geo_scattering') %>
            <small> (disabled)</small></span>

          <% end -%>
        <% end %>
      </li>


      <li>
        <%= link_to(dashboard_stats_export_path, class: current_menu_item_class?(dashboard_stats_export_path)) do %>
          <% cache('icon-cloud-download') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-cloud-download' } %>
          <% end -%>
          <%= t('dashboard.menu.reports_export') %>
        <% end %>
      </li>

      <li>
        <%= link_to(dashboard_stats_errors_path, class: current_menu_item_class?(dashboard_stats_errors_path)) do %>
          <% cache('icon-bug') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-bug' } %>
          <% end -%>
          <%= t('dashboard.menu.errors') %>
        <% end %>
      </li>

      <li>
        <%= link_to(dashboard_stats_heatmaps_path, class: current_menu_item_class?(dashboard_stats_heatmaps_path)) do %>
          <% cache('icon-thermostat-full') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-thermostat-full' } %>
          <% end -%>
          <%= t('dashboard.menu.heatmaps') %> <span class="tag tag-danger">soon</span>
        <% end %>
      </li>
      <li>
        <%= link_to(dashboard_stats_events_path, class: current_menu_item_class?(dashboard_stats_events_path)) do %>
          <% cache('icon-volume-up') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-volume-up' } %>
          <% end -%>
          <%= t('dashboard.menu.events') %> <span class="tag tag-danger">soon</span>
        <% end %>
      </li>

      <!--<li>
        <%= link_to(dashboard_stats_events_path, class: current_menu_item_class?(dashboard_stats_events_path), id: 'dashboard_stats_session_recording_path') do %>
          <% cache('icon-videocam') do %>
            <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-videocam' } %>
          <% end -%>
          <%= t('dashboard.menu.sessions') %>
          <div class="tag tag-danger">soon</div>
        <% end %>
      </li>-->

    </ul>
  <% end %>

  <% unless current_domain.nil? %>
    <% if current_user.own_domain(current_domain) %>
      <p class="menu-label collapse-button">
        <%= t('dashboard.menu.configuration') %>
        <% cache('icon-up-down') do %>
          <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-cheveron-down', :svg_class => "icon-up" } %>
          <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-cheveron-up', :svg_class => "icon-down" } %>
        <% end %>
      </p>
      <ul class="menu-list  collapsible-list">
        <li>
          <%= link_to(settings_dashboard_domain_path(current_domain)) do %>
            <% cache('icon-cog') do %>
              <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-cog' } %>
            <% end -%>
            <%= t('dashboard.menu.configuration') %>
          <% end -%>

          <%= link_to(dashboard_domain_api_keys_path(current_domain), class: current_menu_item_class?(dashboard_domain_api_keys_path(current_domain))) do %>

            <% cache('icon-key') do %>
              <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-key' } %>
            <% end -%>
            <%= t('dashboard.menu.api_keys') %>
          <% end -%>
        </li>
      </ul>

      <p class="menu-label  collapse-button">
        <%= t('dashboard.menu.team_settings') %>
        <% cache('icon-up-down') do %>
          <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-cheveron-down', :svg_class => "icon-up" } %>
          <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-cheveron-up', :svg_class => "icon-down" } %>
        <% end %>
      </p>

      <ul class="menu-list collapsible-list">
        <li>
          <%= link_to(dashboard_team_domain_path(current_domain), class: current_menu_item_class?(dashboard_team_domain_path(current_domain))) do %>
            <% cache('icon-user-group') do %>
              <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-user-group' } %>
            <% end %>
            <%= t('dashboard.menu.members') %>
          <% end %>
        </li>
        <li>
          <%= link_to(new_dashboard_team_domain_path(current_domain), class: current_menu_item_class?(new_dashboard_team_domain_path(current_domain))) do %>
            <% cache('icon-user-add') do %>
              <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-user-add' } %>
            <% end %>
            <%= t('dashboard.menu.add_member') %>
          <% end %>
        </li>
        <li>

          <%= link_to(sent_invitations_dashboard_team_domain_path(current_domain), class: current_menu_item_class?(sent_invitations_dashboard_team_domain_path(current_domain))) do %>
            <% cache('icon-external-window') do %>
              <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-external-window' } %>
            <% end %>
            <%= t('dashboard.menu.sent_invitations') %>
          <% end %>
        </li>
      </ul>
    <% end %>



    <p class="menu-label">
      <%= t('dashboard.menu.domains') %>
    </p>
    <ul>
      <li>
        <%= form_tag('/dashboard/set-current-domain') do %>

          <label><%= t('Change domain') %></label>
          <%= select_tag(:domain_id, options_from_collection_for_select(@my_domains, 'id', 'name', current_domain.nil? ? nil : current_domain.id)) %>
          <%= submit_tag t('Select') %>
          <%= link_to(new_dashboard_domain_path, class: 'inline-menu-button') do%>
            +
          <% end %>
        <% end -%>
      </li>
    </ul>
  <% end %>

  <hr/>
  <p class="menu-label">
    <%= t('dashboard.menu.Other_Domains') %>
  </p>
  <%= link_to(dashboard_domains_received_invitations_path, class: 'icon-container ' + current_menu_item_class?(dashboard_domains_received_invitations_path)) do %>
    <% cache('icon-external-window') do %>
      <%= render :partial => 'shared/icon', :locals => { :icon => 'icon-external-window' } %>
    <% end %>
    <%= t('dashboard.menu.invitations') %>
    <% if admin_received_invitations_count > 0 %>
      (<%= admin_received_invitations_count %>)
    <% end %>
  <% end %>
  <hr/>

  <!--
  <p class="menu-label collapse-button">
    <%#= t('dashboard.menu.account_settings') %>
    <%# cache('icon-up-down') do %>
      <%#= render :partial => 'shared/icon', :locals => {:icon => 'icon-cheveron-down', :svg_class => "icon-up"} %>
      <%#= render :partial => 'shared/icon', :locals => {:icon => 'icon-cheveron-up', :svg_class => "icon-down"} %>
    <%# end %>
  </p>

  <ul class="menu-list collapsible-list">
    <li>
      <%#= link_to(subscription_path, class: current_menu_item_class?(subscription_path)) do %>
        <%#= t('dashboard.menu.rate_usage') %>
      <%# end %>
    <li><a><%#= t('dashboard.menu.advanced') %></a></li>
    <li>
      <%# if current_plan.nil? %>
        <%#= link_to("Subscribe", dashboard_account_plan_subscribe_url) %>
      <%# else %>
        10 days to ends
      <%# end %>
    </li>-->
  </ul>
  <span>
    <small class="font-size-tiny"><%= current_user.email %></small>
  </span>
  <div class=" has-background-warning p-2 mt-2 b-4 is-size-7">
    <span>
      Please note, this is an early stage release, you may find errors or bugs. Please feel free
      to <%= link_to 'report', contact_path(subject: "[BUG]") %> any error.
    </span>
  </div>
</nav>

app/views/shared/_select_period_generic.html.erb
<select <%= "@change=#{event}" %>>

  <option selected="selected" value="year"><%= t('Last Year') %>
    :  <%= Date.today.strftime("%Y") %></option>


  <option value="month"><%= t('This month') %>
    :  <%= Date.today.strftime("%B") %></option>


  <option value="week"><%= t('This week') %>
    :  <%= Date.today.weeks_ago(1).strftime("%d %B") %>
    - <%= Date.today.strftime("%d %B") %></option>


  <option value="day"><%= t('today') %> <%= Date.today.strftime("%B, %Y") %></option>
</select>

app/views/shared/_select_period_inputs.html.erb
<% format = "%Y-%m-%d" %>
<div class="field-label is-normal">
  <label class="label">from</label>
</div>
<div class="field">
  <p class="control">
    <input
      <%= "@change=#{startEvent}" %>
      type="date"
      class="input is-small"
      value="<%= Date.today.weeks_ago(1).strftime(format) %>"
      min="<%= Date.today.years_ago(1).strftime(format) %>" max="<%= Date.today.strftime(format) %>">
  </p>
</div>
<div class="field-label is-normal">
  <label class="label">to</label>
</div>
<div class="field">
  <p class="control">
    <input
      <%= "@change=#{endEvent}" %>
      type="date"
      class="input is-small"
      value="<%= Date.today.weeks_ago(1).strftime(format) %>"
      min="<%= Date.today.years_ago(1).strftime(format) %>" max="<%= Date.today.strftime(format) %>">

  </p>
</div>

app/views/shared/_svg_dynamic_circle.html.erb
<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 20 20">
  <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
    <stop offset="0%" style="stop-color:rgb(255,255,255);stop-opacity:1"/>
    <stop offset="100%" style="stop-color:rgb(72,179,255);stop-opacity:1"/>
  </linearGradient>
  <circle r="10" cy="10" cx="10" stroke="none"
          fill="<%= color || 'url(#grad1)' %>"/>

</svg>