config/routes.rb
Rails.application.routes.draw do

  ### Internal routes for apps communications
  namespace :hooks do
    post '/screenshot' => 'heatmaps#screenshot'
  end
  # collector resources !!!!!
  post 'collect' => 'api/sdk/v1/collect#index'

  namespace :api do
    namespace :ext do
      namespace :v1 do
        get 'views' => 'views#index'
      end
    end
  end

  devise_for :users, path: 'accounts'

  if ENV["UNK_APP_IS_BILLABLE"]
    # TODO remove this
    post '/billing/webhook' => 'billings/webhook'
  end

  authenticate :user do
    # dashboard
    namespace :dashboard do
      get '/' => 'stats#index'
      get '/notify' => 'notifications#notify'
      get '/domains/received-invitations' => 'domains_teams#received_invitations'
      post '/domains/accept-invitation/:domain_id' => 'domains_teams#accept_invitation', as: 'accept_admin_invitation'
      delete '/domains/decline-invitation/:domain_id' => 'domains_teams#decline_invitation', as: 'decline_admin_invitation'

      # accounts and subscribe
      get 'account/plan/current' => 'plan#current_plan'
      get 'account/plan/current/upgrade' => 'plan#upgrade'
      get 'account/plan/current/confirm-upgrade' => 'plan#upgrade'
      get 'account/plan/subscribe' => 'plan#subscribe'
      post 'account/plan/confirm-subscribe' => 'plan#confirm_subscribe'

      # change current domain
      post '/set-current-domain' => 'dashboard#set_current_domain'

      # stats for current domain
      scope :stats, as: 'stats' do
        get '/' => 'stats#overview'
        %w(summary pages devices events errors geo heatmaps export).each do |route|
          get "/#{route}" => "stats##{route}"
        end
      end

      # domains resources
      resources :domains do
        member do
          get 'settings'
          post 'settings'
        end
        member do
          scope :team, as: 'team' do
            get '/' => 'domains_teams#index'
            delete '/delete/:admin_domain_id' => 'domains_teams#delete_member', as: 'delete_member'
            get '/new' => 'domains_teams#new'
            post '/' => 'domains_teams#invite', as: 'invite'
            get '/sent-invitations' => 'domains_teams#sent_invitations'
          end
        end
        resources :api_keys
      end
    end
    # api
    namespace :api do
      get '/overview' => 'overview#index'
      get '/overview/top_pages' => 'overview#top_pages'
      get '/pages/summary' => 'pages#summary'
      get '/pages/views' => 'pages#views'
      get '/pages/weekly_by_days' => 'pages#weekly_by_days'
      get 'pages/:page_id/views' => 'pages#page_views_details'
      get '/geo' => 'geo#index'
      get '/devices' => 'devices#index'

      get '/errors' => 'errors#index'

      # TODO
      get '/events' => 'events#index'
      # clicks and events
      get '/heatmaps' => 'heatmaps#index'
      get '/export' => 'export#index'
      post '/export/pdf' => 'export#as_pdf'
    end

    # admin
    namespace :admin do
      get '/' => 'admin#index'
      resources :users, only: [:index, :show]
      resources :contacts, only: [:index, :show]
    end

    get '/subscription' => 'dashboard/subscription#index'
  end

  authenticated :user do
    scope :welcome do
      root 'welcome#pages', as: 'home_auth_path'
    end
    root 'dashboard/stats#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#pages', as: 'home_path'

  post '/contact' => 'contact#contact_us'
  get '/contact/' => 'contact#index'

  mount Sidekiq::Web => '/sidekiq'

  get "/:page" => "welcome#pages", :as => 'public_pages'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def pages
    @page = params[:page] || 'home'
    if @page == 'welcome'
      @page = 'home'
    end
    if valid_page?
      render "welcome/page"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private

  def valid_page?
    @page = @page.gsub(/-/, '_')
    File.exist?(Pathname.new(Rails.root + "app/views/welcome/_#{@page}.html.erb"))
  end

end

app/views/welcome/home/_documentation.html.erb
<style>
  #sdk_integration .subtitle {
    text-decoration: underline;
  }
</style>
<section id="sdk_integration" class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Documentation</h1>
      <div>
        <h1 class="subtitle ">I - In unk dashboard</h1>
        <h2>1- Configure domain</h2>
        <h2>2- Set up allowed origins</h2>
        <h2>3- Create your api key </h2>
        <br/>
        <h1 class="subtitle"> II - In your application (web site)</h1>
        <h2>4- Include the js script</h2>
        <span class="code">&lt;script <span class="attr-name">src</span>="<span class="attr-value">https://www.unknownanalytics.com/sdk.js</span>"&gt;&lt;/script&gt;</span>
        <br/>* If you apply a
        <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP"><span class="code">Content-Security-Policy</span></a>
        constraints,
        you can download the js file and serve it from your own server.
        <h1>5- Init the client app instance with your api key </h1>
        <span class="code"><span class="attr-value">unkAnalytics</span>(&lt;your_api_key&gt;);</span>
      </div>
      <br/>

      <a href="guide#doc_getting_started">See full documentation here</a>
    </div>
  </div>
</section>

app/views/welcome/home/_features.html.erb
<section class="hero is-fullheight" id="features_container">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Unknown analytics</h1>

      <div class="columns">
        <div class="column">
          <figure>
            <div class="icon-boxed">
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-dashboard'} %>
            </div>
            <figcaption>
              <p>Analytics / Track pages : get your website, analytics and key metrics </p>
            </figcaption>
          </figure>
        </div>

        <div class="column">
          <figure>
            <div class="icon-boxed">
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-bug'} %>
            </div>
            <figcaption>
              <p>Know better about pages performance on users devices with multiple connection types (*) </p></figcaption>
          </figure>
        </div>
        <div class="column">
          <figure>
            <div class="icon-boxed">
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-widget-add'} %>
            </div>
            <figcaption>
              <p> Plug and play : Easy Set up just add the sdk script and get your analytics in your
                dashboard.</p>
            </figcaption>
          </figure>
        </div>
      </div>

      <div class="columns">


        <div class="column">
          <figure>
            <div class="icon-boxed">
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-globe'} %>
            </div>
            <figcaption>
              <p>Anonymous Geo analysis : Geographic analysis in unknown mode </p></figcaption>
          </figure>
        </div>
        <div class="column">
          <figure>
            <div class="icon-boxed">
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-server'} %>
            </div>
            <figcaption>
              <p>Data ownership and protection : you own the data, we store it in a private and secured cloud
                platform. Delete it anytime.</figcaption>
          </figure>
        </div>
        <div class="column">
          <figure>
            <div class="icon-boxed">
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-security-important'} %>
            </div>
            <figcaption>
              <p>Secure by design : No cookies, no local storage, no session. No private data are collected from
                user.</p>
            </figcaption>
          </figure>
        </div>
      </div>
      <small>* This feature is only available for some platforms.</small>
    </div>

  </div>
</section>

app/views/welcome/home/_footer.html.erb
<style>
  #unk_footer {
    margin-bottom: 0;
    background: ghostwhite url("<%=  asset_path('landing/waves.svg') %>");
  }
</style>
<footer class="big-footer">
  <br/>
  <div class="container">
    <div class="columns">

      <div class="column content">
        <h4>Features</h4>
        <a class="is-link"><%= link_to t("Privacy Policy"), public_pages_path(:page => 'privacy-policy') %></a><br/>
        <%= link_to 'About us', '/team' %><br/>
        <%= link_to 'Contact us', contact_path %>

      </div>
      <div class="column content">
        <h4>Resources</h4>
        <a class="is-link"><%= link_to t("Guide"), public_pages_path(:page => 'guide') %></a><br/>
        <a class="is-link"><%= link_to t("FAQ"), public_pages_path(:page => 'faq') %></a></a><br/>
        <a class="is-link"><%= link_to t("Api"), public_pages_path(:page => 'api') %></a></a><br/>
      </div>

      <div class="column content">
        <h4>More </h4>
        <a class="is-link"><%= link_to t("Open source"), public_pages_path(:page => 'open-source') %></a><br/>
        <a class="is-link" href="https://blog.unknownAnalytics.com">Blog</a><br/>
        <a class="is-link" href="https://gitlab.com/unknown-inc">Gitlab</a><br/>
      </div>
    </div>
  </div>
</footer>
<div class="column content is-small" id="unk_footer">
  <div class="column content is-small has-text-centered">
    © <%= Date.today.strftime("%Y") %> Unknown Analytics
    <div class="has-text-centered">A
      <small><a href="https://www.380squares.xyz">380Squares</a></small>
      product
    </div>
  </div>
</div>

app/views/welcome/home/_hero.html.erb
<section class="hero is-fullheight-with-navbar" id="hero_container">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-desktop">
        <div class="column">
          <h1 class="title is-size-3">
            <%= t('welcome.hero') %>
          </h1>
          <p class="subtitle">
            <%= t('welcome.hero_subtitle') %>
          </p>
          <div class="buttons">
            <div>

              <%= link_to(new_user_session_path, class: "button  is-primary is-rounded is-link register-button") do %>
                <strong> <%= t('welcome.start_free_trial') %></strong>
              <% end %>
              <%= link_to('#demo', class: "button is-rounded") do %>
                <strong> <%= t('welcome.watch_demo') %></strong>
                <br/>
              <% end %>

              <br/>
              <small class="ml-1 is-size-7">no credit card required</small>
            </div>
          </div>
        </div>
        <div class="column">
          <div id="box_1" class="box">
            <h1>
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-target'} %>
              <%= t('PageViews ') %>
              <!-- &nbsp;<div class="views-number-animation tag">7777</div> -->
            </h1>
            <div>
              <svg width="100%" height="25%" viewBox="0 0 300 75">
                <defs>
                  <linearGradient id="linear" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0" stop-color="#ffbe88"></stop>
                    <stop offset="0.5" stop-color="#ffa4bc"></stop>
                    <stop offset="1" stop-color="#ff94db"></stop>
                  </linearGradient>
                </defs>
                <path fill="none" stroke="url(#linear)" d="M8 66.99409117976404L19.64131103234081 60.22381512077443S28.285714285714285 55.19646070785843 35.82132902743442 48.62268626204953L41.03581382970843 44.0737744458089S48.57142857142857 37.5 55.09067075779435 29.91715875706812L62.33790067077708 21.48756029912064S68.85714285714286 13.90471905618876 75.37638504350863 21.487560299120645L82.62361495649137 29.917158757068115S89.14285714285714 37.5 94.80976140561769 29.26069201469527L103.76166716581086 16.24520680554068S109.42857142857142 8.005898820235949 113.83796949788308 16.98126559081143L125.30488764497406 40.32227370133015S129.71428571428572 49.29764047190562 138.35868711575174 44.270282874684966L141.355598598534 42.52735759722066S150 37.5 155.66690426276054 45.739307985304734L164.61881002295374 58.75479319445931S170.28571428571428 66.99410117976404 180.28571428571428 66.99410117976404L180.57142857142856 66.99410117976404S190.57142857142856 66.99410117976404 200.1736961374494 64.20188743605743L201.25487529112198 63.88749468751786S210.85714285714283 61.09528094381124 215.2665409264545 52.119914173235756L226.73345907354548 28.778906062717052S231.14285714285714 19.803539292141572 236.1155493499323 28.479502190500114L246.45587922149625 46.520497809499886S251.42857142857142 55.19646070785843 255.83796949788308 46.221093937282944L267.30488764497403 22.88008582676424S271.7142857142857 13.90471905618876 275.2836384019045 23.24601026197977L292 66.99411117976405" style="transition: stroke-dashoffset 2000ms ease 0s; stroke-dasharray: 433.849, 433.849; stroke-dashoffset: 0;"></path>
              </svg>

            </div>

          </div>

          <div id="box_2" class="box">
            <h1>
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-user', :css_class => ''} %>

              <%= t('Heatmaps ') %>
            </h1>
            <svg width="150" height="100" viewBox="0 0 200 600" xmlns="http://www.w3.org/2000/svg">
              <linearGradient id="shape_gradient" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0" stop-color="#ffbe88"></stop>
                <stop offset="0.5" stop-color="#ffa4bc"></stop>
                <stop offset="1" stop-color="#ff94db"></stop>
              </linearGradient>
              <linearGradient id="shape_gradient_blue" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0.3" stop-color="#4bcffa"></stop>
                <stop offset=".7" stop-color="#199ff9"></stop>
                <stop offset="1" stop-color="#ff94db"></stop>
              </linearGradient>
              <g xmlns="http://www.w3.org/2000/svg" transform="translate(80, 250)" style="
              opacity: 0.8;
              ">

                <path d="M158.3,-198.7C205.7,-183.4,245,-137.9,250.1,-89.1C255.2,-40.3,226,11.8,196.5,51.8C166.9,91.7,136.9,119.5,104.1,150.7C71.3,181.8,35.7,216.4,-6.2,224.9C-48,233.4,-96,215.8,-135.3,186.7C-174.6,157.7,-205.2,117.2,-218,72.2C-230.8,27.2,-225.7,-22.2,-207.7,-64.3C-189.6,-106.3,-158.6,-140.9,-121.8,-159.7C-85,-178.4,-42.5,-181.2,6.5,-190.1C55.4,-199,110.9,-214,158.3,-198.7Z" fill="url(#shape_gradient)"></path>
                <path d="M107.2,-150.9C142.7,-121.8,177.9,-95.5,188,-61.7C198.1,-27.9,183.2,13.4,176,63.9C168.8,114.4,169.4,174.1,141.3,200.8C113.2,227.5,56.6,221.3,8.9,209C-38.8,196.7,-77.6,178.5,-110.9,153.4C-144.2,128.4,-171.9,96.7,-171.9,63.7C-171.8,30.7,-143.9,-3.5,-128.8,-39.3C-113.6,-75,-111.2,-112.3,-91.8,-146.7C-72.5,-181.1,-36.2,-212.6,-0.2,-212.3C35.9,-212,71.7,-180,107.2,-150.9Z" fill="url(#shape_gradient)"></path>

                <path d="M126.6,-191.5C156.6,-177.7,168.4,-130,177.2,-87.7C186.1,-45.3,192,-8.4,181.4,22.1C170.8,52.6,143.6,76.7,117.1,94C90.5,111.4,64.7,121.9,36.7,134.3C8.7,146.8,-21.4,161.2,-48.8,157.2C-76.2,153.3,-100.8,131,-135.8,108C-170.7,85,-216,61.3,-235.7,24.6C-255.5,-12.1,-249.6,-61.7,-225.3,-97.8C-200.9,-133.9,-158,-156.6,-117.4,-165.5C-76.8,-174.5,-38.4,-169.7,5,-177.4C48.3,-185.2,96.6,-205.3,126.6,-191.5Z" fill="url(#shape_gradient_blue)"></path>
                <path d="M63,-58.2C86.4,-20.9,113.4,5.6,118.8,45.1C124.1,84.7,107.8,137.4,71.6,158.7C35.4,179.9,-20.7,169.7,-79.3,147.9C-138,126.1,-199.1,92.8,-210.1,47.3C-221,1.8,-181.6,-55.8,-138.2,-97.7C-94.9,-139.7,-47.4,-165.8,-13.8,-154.8C19.8,-143.8,39.6,-95.6,63,-58.2Z" fill="#fcb900"></path>

              </g>
            </svg>

          </div>


          <div id="box_3" class="box">
            <h1>
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-bolt', :css_class => ''} %>
              <%= t('Performance') %>&nbsp;<!--<div class="views-number-animation tag">9999</div>-->
            </h1>
            <div id="hero_events_chart">

            </div>
          </div>
          <div id="box_4" class="box">
            <h1>
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-bolt', :css_class => ''} %>
              <%= t('Campaigns') %>&nbsp;<!--<div class="views-number-animation tag">9999</div>-->
            </h1>
            <div id="hero_campaigns">

            </div>
          </div>

          <div id="box_5" class="box">
            <h1>
              <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-user', :css_class => ''} %>
              <%= t('Devices ') %>
            </h1>
            <svg viewBox="-1 -1 2 2" width="200" height="120">
              <defs>
                <linearGradient id="gradient2" x1="0%" y1="0%" x2="0%" y2="100%">
                  <stop offset="0%" stop-color="#ffd392"></stop>
                  <stop offset="100%" stop-color="#ff3898"></stop>
                </linearGradient>
              </defs>
              <circle class="circle" r="0.6" cx="0" cy="0" stroke="url(#gradient2)" fill="transparent" stroke-width=".7"></circle>

              <path class="circle" d="M 1 0 A 1 1 0 0 1 0.8090169943749475 0.5877852522924731 L 0 0" fill="#4b9dc6"></path>


            </svg>

          </div>

        </div>
      </div>
      <div id="map_hero" class="welcome-map-dots">
        <%= render 'shared/map_dots' %>
      </div>
    </div>
  </div>
</section>

app/views/welcome/home/_integration.html.erb
<style>
  #plugins svg {
    width: 104px;
    height: 104px;
    margin: 10px;
    --primary: indianred;
    top: 4px;
    position: relative;
  }
</style>
<!--<section class="section is-medium" id="plugins">
  <div class="container">
    <div class="title-wrapper">
      <h2 class="title is-2"><%#= t('welcome.custom_integration') %></h2>
      <h3 class="subtitle is-5 is-muted">extend your analytics with custom integrations</h3>
      <div class="divider is-centered"></div>
    </div>

    <div class="content-wrapper">
      <div class="columns">
        <div class="column is-one-third">
          <div class="feature-card is-bordered has-text-centered revealOnScroll delay-1" data-animation="fadeInLeft">
            <div>
              <span class="shadow-text-bottom">E commerce</span>
            </div>
            <div class="card-icon">
              <%#= render :partial => 'shared/icon', :locals => {:icon => 'icon-shopping-cart'} %>
            </div>
            <div class="card-text">
              <p>Expend your e-shop analysis with custom details and metrics</p>
            </div>

          </div>
        </div>
        <div class="column">
          <div class="feature-card is-bordered has-text-centered revealOnScroll delay-2" data-animation="fadeInLeft">
            <div>
              <span class="shadow-text-bottom">Custom formatting</span>
            </div>
            <div class="card-icon">
              <%#= render :partial => 'shared/icon', :locals => {:icon => 'icon-tune'} %>
            </div>
            <div class="card-text">
              <p>Customise your exported data so you cas explore it at your own way </p>
            </div>

          </div>
        </div>
        <div class="column">
          <div class="feature-card is-bordered has-text-centered revealOnScroll delay-3" data-animation="fadeInLeft">
            <div>
              <span class="shadow-text-bottom">Plugins</span>
            </div>
            <div class="card-icon">
              <%#= render :partial => 'shared/icon', :locals => {:icon => 'icon-brick'} %>
            </div>
            <div class="card-text">
              <p>Plug your data with external data points (cloud, dumps ...) </p>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>-->

app/views/welcome/home/_pricing.html.erb
<section id="pricing" class="hero">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">Pricing <span class="tag is-danger">Free in beta !</span></h1>
      <table class="table table-bordered is-striped is-fullwidth">
        <thead>
        <tr>
          <th>
            <div>Features</div>
          </th>
          <th>
            <div class="has-text-weight-bold is-size-4">Essential</div>
            <div class="has-text-danger">8€/month</div>
            <p class="p-2">
              100k page views <br/>
              3 domains <br/>
              6 months data retention <br/>
            </p>
          </th>
          <th>
            <div class="has-text-weight-bold is-size-4">Plus</div>
            <div class="has-text-danger">12€/month</div>
            <p class="p-2">
              200k views <br/>
              8 domains <br/>
              12 months data retention <br/>
            </p>
          </th>
          <th>
            <div class="has-text-danger is-size-4">Enterprise</div>
            <%= link_to "Contact us", contact_path(subject: "[Business]"), class: "button has-text-danger is-small" %>
            <p class="p-2">
              Unlimited views <br/>
              Unlimited domains <br/>
              Unlimited data retention <br/>
            </p>
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>
            <div>Page analytics <br/>
              <small>(views, devices, utm campaigns, referrals)</small>
              <br/>
            </div>
          </td>
          <td>
            <div class="check">&#10004;</div>
          </td>
          <td>

            <div class="check">&#10004;</div>
          </td>
          <td>
            <div class="check">&#10004;</div>
          </td>
        </tr>
        <tr>
          <td>
            <div>Geo analytics</div>
          </td>
          <td>
            <div class="check">&#10004;</div>
          </td>
          <td>
            <div class="check">&#10004;</div>
          </td>
          <td>
            <div class="check">&#10004;</div>
          </td>
        </tr>
        <tr>
          <td>
            <div>Performance</div>
          </td>
          <td>
            <div class="check">&#10004;</div>
          </td>
          <td>

            <div class="check">&#10004;</div>
          </td>
          <td>

            <div class="check">&#10004;</div>
          </td>
        </tr>
        <tr>
          <td>
            <div>Domains</div>
          </td>
          <td>
            3 domains
          </td>
          <td>
            8 domains
          </td>
          <td>
            Unlimited
          </td>
        </tr>
        <tr>
          <td>
            <div>Reports</div>
          </td>
          <td>
            1 / day
          </td>
          <td>
            3 / day
          </td>
          <td>
            Unlimited
          </td>
        </tr>
        <tr>
          <td>
            <div>Data retention</div>
          </td>
          <td>
            6 months
          </td>
          <td>
            12 months
          </td>
          <td>
            Unlimited
          </td>
        </tr>
        <tr>
          <td>
            <div>Api</div>
          </td>
          <td>
            1k call
          </td>
          <td>
            3k call
          </td>
          <td>
            Unlimited
          </td>
        </tr>
        <tr>
          <td>
            <div>Support (h/days in week)</div>
          </td>
          <td>
            4/5
          </td>
          <td>
            8/5
          </td>
          <td>
            12/6
          </td>
        </tr>
        <tr>
          <td colspan="4">
            <div class="has-text-weight-bold">Roadmap</div>
          </td>
        </tr>
        <tr>
          <td>
            <div>Heatmaps *</div>
          </td>
          <td>

          </td>
          <td>

          </td>
          <td>

          </td>
        </tr>
        <tr>
          <td>
            <div>Event (click, hover, navigation) *</div>
          </td>
          <td>

          </td>
          <td>

          </td>
          <td>

          </td>
        </tr>
        <tr>
          <td>
            <div>Bugs reporting *</div>
          </td>
          <td>

          </td>
          <td>

          </td>
          <td>

          </td>
        </tr>
        <tr>
          <td>
            <div>Real time Notifications *</div>
          </td>
          <td>

          </td>
          <td>

          </td>
          <td>

          </td>
        </tr>
        <tr>
          <td>
            <div>Screen view *</div>
          </td>
          <td>

          </td>
          <td>

          </td>
          <td>

          </td>
        </tr>
        <tr>
          <td>
            <div>Sandbox *</div>
          </td>
          <td>

          </td>
          <td>

          </td>
          <td>

          </td>
        </tr>
        <tr>
          <td>
            <div>Sandbox Data retention</div>
          </td>
          <td>

          </td>
          <td>

          </td>
          <td>

          </td>
        </tr>
        </tbody>
      </table>
      <div>
        <div>* WIP feature (not yet released). Please contact us if you need more information about product roadmap.
        </div>
      </div>
      <p class="control has-text-centered pt-5">
        <%= link_to(contact_path, class: "button is-link is-info is-bold") do %>
          ONG Startup 50% cut off
        <% end %>
        <%= link_to(contact_path, class: "button is-link is-info is-bold") do %>
          Need Custom features , let's talk
        <% end %>
      </p>
    </div>
  </div>

</section>

app/views/welcome/home/_privacy.html.erb
<section class=" hero" id="principles">
  <div class="container">
    <article class=""><h1 class="title"> Why we do not track your users ? </h1></article>
    <div class="columns  is-desktop">
      <div class="column">
        <figure>
          <div class="icon-boxed">
            <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-no-store'} %>
          </div>
          <figcaption><h3><%= t('welcome.how_we_make_money') %></h3>
            <p>We DO NOT gather any information from your costumer and our business model rely on our clients
              subscriptions. </p></figcaption>
        </figure>
      </div>
      <div class="column">
        <figure>
          <div class="icon-boxed">
            <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-security'} %>
          </div>
          <figcaption><h3>No partnership</h3>
            <p>We DO NOT have any partnerships with organizations that may use your data or your customer's data.</p>
          </figcaption>
        </figure>
      </div>
      <div class="column">
        <figure>
          <div class="icon-boxed">
            <%= render :partial => 'shared/icon', :locals => {:icon => 'icon-security-important'} %>
          </div>
          <figcaption>
            <h3>Where's my Data ? </h3>
            <p>
              All data collected for analysis is stored in
              <a href="https://www.ovhcloud.com/en/about-us/infrastructure-software/">OVH</a> data centres, our cloud
              provider that guarantees data protection and reliability.
            </p>
          </figcaption>
        </figure>
      </div>
    </div>
    <div>

    </div>
    <blockquote>
      In the analytics business, if you're not paying for the service, you or your customer are the product.
    </blockquote>
    <%= link_to('Learn More about security ', '/security-and-data') %>

  </div>

</section>

app/views/welcome/home/_product.html.erb
<section class="hero is-relative" id="product">
  <div class="container">
    <h3 class="title">Product</h3>
    <div class="tabs is-centered">
      <ul>
        <li><a>Page views </a></li>
        <li class="is-active"><a>Dashboard</a></li>
        <li><a>Reports </a></li>
        <li><a>Api </a></li>
        <li><a>Heatmaps & Events <span class="tag tag-danger"> soon</span> </a></li>
        <li><a>Sandbox <span class="tag tag-danger"> soon</span> </a></li>
        <!--        <li><a>Instant notifications</a></li>-->
      </ul>
    </div>
    <div class="hero container">

      <section class="tab-content">
        <div class="block-image">
          <%= image_tag('features/undraw_hologram_fjwp.svg') %>
        </div>
        <div class="block-feature">
          Pages, views, utms, compaings, performances and more without code headache.
        </div>
      </section>
      <section class="tab-content">
        <div class="block-image">
          <%= image_tag('features/undraw_charts_jj6t.svg') %>
        </div>
        <div class="block-feature">
          Get a complete dashboard with clear insights about your site.
        </div>
      </section>
      <section class="tab-content">
        <div class="block-image">
          <%= image_tag('features/undraw_data_report_bi6l.svg') %>
        </div>
        <div class="block-feature">
          Customize your PDF reports with flexible charts, drag & drop tools and ready-to use templates .
        </div>
      </section>


      <section class="tab-content">
        <div class="block-feature">
          Define your rules and get instant notifications.
        </div>
        <div class="block-image">
          <%= image_tag('features/undraw_instant_information_6755.svg') %>
        </div>
      </section>

      <section class="tab-content">
        <div class="block-feature">
          See where users navigate, click. Get clear feedback of your users behaviour.
        </div>
        <div class="block-image">
          <%= image_tag('features/undraw_heatmap_uyye.svg') %>
        </div>
      </section>

      <section class="tab-content">
        <div class="block-feature">
          Sandbox mode for testing before you go life.
        </div>
        <div class="block-image">
          <%= image_tag('features/undraw_work_in_progress_uhmv.svg') %>
        </div>
      </section>
    </div>
  </div>
</section>